### ISSUE TITLE
好好玩哈哈

### ISSUE THREAD

**Issue by xushet** [linyiLYi/pose-monitor#10]
希望能增加切换到前置摄像头的支持![Screenshot_20221105-175211_让爷康康.png](https://user-images.githubusercontent.com/34502902/200113948-eed1fe15-5ce2-490e-a636-ba60b5c95b21.png)

设备小米6 类原生Android11

**Comment by zhengbangbo** [comment]
https://github.com/linyiLYi/pose-monitor/blob/6910be0811122e143a9bb0f517bf48d2bca7818f/android/app/src/main/java/lyi/linyi/posemon/camera/CameraSource.kt#L165-L178

修改这里，应该可以切换前置摄像头。

**Comment by peterhiking** [comment]
小黑子你食不食香煎精鱼
