### ISSUE TITLE
可以实现同时识别多个人吗，我测试了下只能识别一个

### ISSUE THREAD

**Issue by KangKang0928** [linyiLYi/pose-monitor#16]
可以实现同时识别多个人吗，我测试了下只能识别一个。
要实现同时识别多人，可行吗？求大神指个路
（可能性能要求会比较高？同时识别2个人也成）

**Comment by linyiLYi** [comment]
MoveNet MultiPose 是支持多人识别的，可以同时识别多人的姿态。单论这次这个监测不良坐姿的应用，我觉得多人状态下比较好的思路是把用户自己先框出来，然后只分析用户自己的姿态。如果是多个姿态同时识别出来可以做一些适合多人的应用，比如行人计数等

**Comment by KangKang0928** [comment]
感谢
