### ISSUE TITLE
应该是因为麒麟不支持NNAPI，进去直接闪退

### ISSUE THREAD

**Issue by zdian** [linyiLYi/pose-monitor#2]
不把NNAPI设为默认项就可以了。

**Comment by linyiLYi** [comment]
可以在 MainActivity.kt 里面第 56 行 `private var device = Device.NNAPI` 改成 `private var device = Device.GPU`，这样默认计算设备就是 GPU 了。麒麟芯片应该也是有 NPU 的（我要再确认一下），但可能 Tensorflow Lite 的 NNAPI 接口不支持麒麟的 NPU。
